name: left-metrics
on:
  schedule:
    - cron: "0 18 * * 0"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
#       - name: followup
#         uses: lowlighter/metrics@latest
#         with:
#           # Your GitHub token
#           token: ${{ secrets.METRICS }}
#           committer_token: ${{ secrets.GITHUB_TOKEN }}

#           # Options
#           user: Coordinate-Cat
#           template: classic
#           base: header, activity, community, repositories, metadata
#           config_display: large
#           config_padding: 0, 8 + 11%
#           config_timezone: Asia/Tokyo
          
      - name: followup
        uses: lowlighter/metrics@latest
        with:
          filename: followup.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories
      
      - name: isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
      - name: languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
      - name: lines
        uses: lowlighter/metrics@latest
        with:
          filename: lines.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: repositories
          plugin_lines: yes
          
      - name: pagespeed
        uses: lowlighter/metrics@latest
        with:
          filename: pagespeed.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://route23.pages.dev/
          
      - name: stars
        uses: lowlighter/metrics@latest
        with:
          filename: stars.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 8
